import { DataTypes } from 'sequelize'
import { sequelize } from './database.js'


// model is a table in database
// primary keys: {chainId, tokenAddr, timestamp}
export const OptionkPriceModel = sequelize.define('OptionPrice', {
    chainId: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true
    },
    symbol: {  // address of token
        type: DataTypes.STRING,
        allowNull: false,
        primaryKey: true
    },
    timestamp: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true
    },
    markPrice: {
        type: DataTypes.DOUBLE,
        allowNull: false
    }
}, {
    timestamps: false  // disable autogenerated timestamp by sequelize
});
